[[local|localrc]]

disable_service n-net
disable_service ceilometer-acompute

#NEUTRON_REPO=http://10.160.5.251:8080/neutron
NEUTRON_REPO=file:///home/stack/neutron
NEUTRON_BRANCH=stable/juno
REQUIREMENTS_REPO=http://github.com/jerryz1982/requirements.git
REQUIREMENTS_BRANCH=test_fortinet

Q_PLUGIN=ml2
ENABLE_TENANT_VLANS=True
ML2_L3_PLUGIN=router_fortinet
Q_ML2_PLUGIN_MECHANISM_DRIVERS='openvswitch,fortinet'
Q_ML2_PLUGIN_VLAN_TYPE_OPTIONS='network_vlan_ranges=physnet1:1000:2999'
Q_ML2_PLUGIN_TYPE_DRIVERS=local,flat,vlan,gre,vxlan
Q_ML2_TENANT_NETWORK_TYPE=vlan

PROVIDER_NETWORK_TYPE=vlan
PHYSICAL_NETWORK=physnet1
# CHANGEME: bridge for tenant network br-eth*
OVS_PHYSICAL_BRIDGE=br-eth2
Q_USE_PROVIDER_NETWORKING=True
# CHANGEME: nic for tenant network
PUBLIC_INTERFACE=eth2

# generic configuration parameters

DATABASE_PASSWORD=secretsecret
RABBIT_PASSWORD=secretsecret
SERVICE_TOKEN=secretsecret
SERVICE_PASSWORD=secretsecret
ADMIN_PASSWORD=secretsecret

API_RATE_LIMIT="False"
RECLONE="True"

# database configuration parameters

DATABASE_TYPE=mysql

# networking configuration parameters
# CHANGEME: control plane nic
HOST_IP_IFACE=eth1

# logging configuration parameters

LOGFILE=/opt/stack/logs/stack.sh.log
VERBOSE=True
LOG_COLOR=True
SCREEN_LOGDIR=/opt/stack/logs


# generic configuration parameters (compute)

Q_ML2_PLUGIN_MECHANISM_DRIVERS='openvswitch'
ENABLED_SERVICES=n-cpu,q-agt,c-vol,n-novnc
# CHANGEME: hostname or ip of controller
SERVICE_HOST=manager
MYSQL_HOST=$SERVICE_HOST
RABBIT_HOST=$SERVICE_HOST
GLANCE_HOST=$SERVICE_HOST

